Repository prgrms-web-devcourse-final-project/WEB3_4_LoveCodeAnyway_BE, pull requests merged in 2025-04, with the labels that each got.

#45 feat: JWT 토큰 생성 및 검증 유틸 클래스 구현
  .gitignore
  build.gradle
  src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application-secret.default.yml
  src/main/resources/application.yml
  src/test/java/com/ddobang/backend/global/security/jwt/JwtTokenProviderTest.java
Labels: feature

#59 feat: 알림에 SSE 추가 , GEMINI 수정 및 업데이트
  .github/workflows/gemini_code_review.yml
  src/main/java/com/ddobang/backend/domain/alarm/controller/AlarmController.java
  src/main/java/com/ddobang/backend/domain/alarm/entity/AlarmType.java
  src/main/java/com/ddobang/backend/domain/alarm/exception/AlarmErrorCode.java
  src/main/java/com/ddobang/backend/domain/alarm/exception/AlarmErrorCode.java~
  src/main/java/com/ddobang/backend/domain/alarm/exception/SseException.java
  src/main/java/com/ddobang/backend/domain/alarm/infra/EmitterRepository.java
  src/main/java/com/ddobang/backend/domain/alarm/service/AlarmEventService.java
  src/main/java/com/ddobang/backend/domain/alarm/service/AlarmService.java
  src/main/java/com/ddobang/backend/domain/member/entity/Member.java
  src/main/java/com/ddobang/backend/domain/member/entity/Member.java~
  src/main/java/com/ddobang/backend/domain/member/service/MemberService.java
  src/main/java/com/ddobang/backend/global/exception/GlobalExceptionHandler.java
  src/main/resources/application-dev.yml
  src/test/java/com/ddobang/backend/domain/alarm/infra/EmitterRepositoryExtendedTest.java
  src/test/java/com/ddobang/backend/domain/alarm/infra/EmitterRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/alarm/infra/EmitterRepositoryTest.java~
  src/test/java/com/ddobang/backend/domain/alarm/repository/AlarmRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/alarm/service/AlarmEventServiceTest.java
Labels: feature, chore

#63 feat: 모임 등록 및 일지 작성 전용 테마 검색 api 구현 및 테스트 작성
  src/main/java/com/ddobang/backend/domain/region/controller/RegionController.java
  src/main/java/com/ddobang/backend/domain/store/controller/AdminStoreController.java
  src/main/java/com/ddobang/backend/domain/store/controller/StoreController.java
  src/main/java/com/ddobang/backend/domain/theme/controller/ThemeController.java
  src/main/java/com/ddobang/backend/domain/theme/dto/ThemeForDiaryResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/ThemeForPartyResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/ThemesDto.java
  src/main/java/com/ddobang/backend/domain/theme/dto/ThemesResponse.java
  src/main/java/com/ddobang/backend/domain/theme/initData/InitThemeMockData.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepository.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryCustom.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/theme/service/ThemeService.java
  src/main/java/com/ddobang/backend/global/config/SpringdocConfig.java
  src/test/java/com/ddobang/backend/domain/region/controller/RegionControllerTest.java
  src/test/java/com/ddobang/backend/domain/store/controller/AdminStoreControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeStatRepositoryTest.java
Labels: feature

#61 feat: 카카오 OAuth2 로그인 및 JWT 인증/인가 설정 적용 (#37)
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/java/com/ddobang/backend/BackendApplication.java
  src/main/java/com/ddobang/backend/domain/auth/exception/AuthException.java
  src/main/java/com/ddobang/backend/domain/auth/exception/OAuth2ErrorCode.java
  src/main/java/com/ddobang/backend/domain/member/entity/Member.java
  src/main/java/com/ddobang/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/ddobang/backend/domain/member/service/MemberService.java
  src/main/java/com/ddobang/backend/global/exception/JwtErrorCode.java
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtExceptionFilter.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/java/com/ddobang/backend/global/util/CookieUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-secret.default.yml
  src/main/resources/application.yml
  src/test/java/com/ddobang/backend/global/security/jwt/JwtTokenProviderTest.java
Labels: feature

#70 fix: SecurityConfig에서 MVC 요청 충돌 이슈 해결 (#69)
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/test/java/com/ddobang/backend/global/security/TestSecurityConfig.java
Labels: bug

#67 feat: 탈출일지 기능 완성
  src/main/java/com/ddobang/backend/domain/diary/controller/DiaryController.java
  src/main/java/com/ddobang/backend/domain/diary/converter/DiaryConverter.java
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryFilterRequest.java
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryRequestDto.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryDto.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryListDto.java
  src/main/java/com/ddobang/backend/domain/diary/entity/Diary.java
  src/main/java/com/ddobang/backend/domain/diary/entity/DiaryStat.java
  src/main/java/com/ddobang/backend/domain/diary/exception/DiaryErrorCode.java
  src/main/java/com/ddobang/backend/domain/diary/initdata/DiaryInitData.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepository.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepositoryCustom.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryStatRepository.java
  src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
  src/main/java/com/ddobang/backend/domain/theme/entity/Theme.java
  src/main/java/com/ddobang/backend/domain/theme/initData/InitThemeMockData.java
  src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
  src/test/java/com/ddobang/backend/global/security/jwt/JwtTokenProviderTest.java
Labels: refactor, feature, test

#71 fix: JWT인증 로직 오류 수정(헤더 > 쿠키), Role명 수정
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/ddobang/backend/global/util/CookieUtil.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
Labels: bug

#81 feat: 이미지 업로드 기능 구현
  src/main/java/com/ddobang/backend/domain/board/repository/AttachmentRepository.java
  src/main/java/com/ddobang/backend/domain/board/types/PostType.java
  src/main/java/com/ddobang/backend/domain/diary/entity/Diary.java
  src/main/java/com/ddobang/backend/domain/member/entity/Member.java
  src/main/java/com/ddobang/backend/domain/upload/controller/UploadController.java
  src/main/java/com/ddobang/backend/domain/upload/exception/UploadErrorCode.java
  src/main/java/com/ddobang/backend/domain/upload/exception/UploadException.java
  src/main/java/com/ddobang/backend/domain/upload/service/UploadService.java
  src/main/java/com/ddobang/backend/domain/upload/types/FileUploadTarget.java
  src/main/java/com/ddobang/backend/global/entity/Attachment.java
  src/main/java/com/ddobang/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddobang/backend/global/util/Ut.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/ddobang/backend/domain/party/controller/PartyControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/upload/controller/UploadControllerTest.java
Labels: feature, test

#83 feat: 관리자 전용 테마 관리 api, 사용자 전용 테마 등록 api 구현
  src/main/java/com/ddobang/backend/domain/diary/controller/DiaryController.java
  src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
  src/main/java/com/ddobang/backend/domain/store/controller/AdminStoreController.java
  src/main/java/com/ddobang/backend/domain/store/controller/StoreController.java
  src/main/java/com/ddobang/backend/domain/store/dto/StoreResponse.java
  src/main/java/com/ddobang/backend/domain/store/entity/Store.java
  src/main/java/com/ddobang/backend/domain/store/repository/StoreRepository.java
  src/main/java/com/ddobang/backend/domain/store/service/StoreService.java
  src/main/java/com/ddobang/backend/domain/theme/controller/AdminThemeController.java
  src/main/java/com/ddobang/backend/domain/theme/controller/ThemeController.java
  src/main/java/com/ddobang/backend/domain/theme/dto/ThemeForDiaryResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeFilterRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForAdminRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForMemberRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/SimpleThemeResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeDetailResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeForAdminResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeForPartyResponse.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemesResponse.java
  src/main/java/com/ddobang/backend/domain/theme/entity/Theme.java
  src/main/java/com/ddobang/backend/domain/theme/initData/InitThemeMockData.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepository.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryCustom.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepository.java
  src/main/java/com/ddobang/backend/domain/theme/service/ThemeService.java
  src/main/java/com/ddobang/backend/domain/theme/service/ThemeTagService.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/ddobang/backend/domain/store/controller/AdminStoreControllerTest.java
  src/test/java/com/ddobang/backend/domain/store/repository/StoreRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/store/service/StoreServiceTest.java
  src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeStatRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/service/ThemeServiceTest.java
  src/test/java/com/ddobang/backend/domain/theme/service/ThemeTagServiceTest.java
Labels: feature

#88 refactor: 코드 리뷰 기반 리팩토링
  src/main/java/com/ddobang/backend/domain/diary/converter/DiaryConverter.java
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryFilterRequest.java
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryRequestDto.java
  src/main/java/com/ddobang/backend/domain/diary/entity/Diary.java
  src/main/java/com/ddobang/backend/domain/diary/exception/DiaryErrorCode.java
  src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
  src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
Labels: refactor, test

#86 feat: 테마 태그 목록 요청 로직 변경 및 테마 통계 낙관적 락 반영
  src/main/java/com/ddobang/backend/domain/region/controller/RegionController.java
  src/main/java/com/ddobang/backend/domain/region/repository/RegionRepository.java
  src/main/java/com/ddobang/backend/domain/region/service/RegionService.java
  src/main/java/com/ddobang/backend/domain/theme/controller/ThemeController.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeFilterRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForAdminRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/request/ThemeForMemberRequest.java
  src/main/java/com/ddobang/backend/domain/theme/dto/response/ThemeTagResponse.java
  src/main/java/com/ddobang/backend/domain/theme/entity/ThemeStat.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepository.java
  src/main/java/com/ddobang/backend/domain/theme/service/ThemeService.java
  src/main/java/com/ddobang/backend/domain/theme/service/ThemeTagService.java
  src/main/java/com/ddobang/backend/global/exception/GlobalErrorCode.java
  src/main/java/com/ddobang/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/test/java/com/ddobang/backend/domain/region/controller/RegionControllerTest.java
  src/test/java/com/ddobang/backend/domain/region/repository/RegionRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/region/service/RegionServiceTest.java
  src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/repository/ThemeTagRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/theme/service/ThemeServiceTest.java
Labels: feature

#97 feat: 테마 통계 및 평가 정보 입력
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryFilterRequest.java
  src/main/java/com/ddobang/backend/domain/diary/dto/request/DiaryRequestDto.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryDto.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryListDto.java
  src/main/java/com/ddobang/backend/domain/diary/entity/DiaryStat.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryStatRepository.java
  src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
  src/main/java/com/ddobang/backend/domain/stat/calculator/ThemeStatCalculator.java
  src/main/java/com/ddobang/backend/domain/stat/dto/ThemeStatResult.java
  src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
  src/main/java/com/ddobang/backend/global/util/Ut.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/ddobang/backend/domain/stat/calculator/ThemeStatCalculatorTest.java
  src/test/java/com/ddobang/backend/domain/theme/controller/ThemeControllerTest.java
Labels: refactor, feature, test

#92 feat: CORS 설정 및 preflight 요청 대응 통합 테스트 추가
  src/main/java/com/ddobang/backend/global/auth/controller/AuthController.java
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/test/java/com/ddobang/backend/global/auth/controller/AuthControllerTest.java
  src/test/java/com/ddobang/backend/global/config/CorsConfigIntegrationTest.java
Labels: feature, test

#120 test: MemberTestFactory 추가
  src/test/java/com/ddobang/backend/support/MemberTestFactory.java
Labels: test

#121 fix: JWT 토큰 구조 변경 및 OAuth2 회원 조회 로직 수정
  src/main/java/com/ddobang/backend/domain/member/repository/MemberRepository.java
  src/main/java/com/ddobang/backend/domain/member/service/MemberService.java
  src/main/java/com/ddobang/backend/global/auth/service/AuthService.java
  src/main/java/com/ddobang/backend/global/security/LoginMemberProvider.java
  src/main/java/com/ddobang/backend/global/security/SecurityConfig.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtPayloadExtractor.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenFactory.java
  src/main/java/com/ddobang/backend/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/ddobang/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/ddobang/backend/global/auth/AuthIntegrationTest.java
  src/test/java/com/ddobang/backend/global/auth/controller/AuthControllerTest.java
  src/test/java/com/ddobang/backend/global/auth/service/AuthServiceTest.java
  src/test/java/com/ddobang/backend/global/security/LoginMemberProviderTest.java
  src/test/java/com/ddobang/backend/global/security/jwt/JwtTokenProviderTest.java
Labels: test

#124 feat: OAuth2 로그인 성공 시 프론트엔드 도메인으로 리다이렉트 처리
  src/main/java/com/ddobang/backend/BackendApplication.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2RedirectProperties.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: refactor, feature

#125 fix: OAuth2 로그인 성공 시 프론트엔드 도메인으로 리다이렉트 처리 로직 수정
  src/main/java/com/ddobang/backend/global/exception/oauth2/OAuth2ErrorCode.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2RedirectProperties.java
  src/main/java/com/ddobang/backend/global/security/oauth/OAuth2SuccessHandler.java
  src/main/resources/application.yml
Labels: feature

#127 feat: 사용자 분석 페이지 api 구현
  src/main/java/com/ddobang/backend/domain/diary/converter/DiaryConverter.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryDto.java
  src/main/java/com/ddobang/backend/domain/diary/dto/response/DiaryListDto.java
  src/main/java/com/ddobang/backend/domain/diary/entity/Diary.java
  src/main/java/com/ddobang/backend/domain/diary/entity/DiaryStat.java
  src/main/java/com/ddobang/backend/domain/diary/exception/DiaryErrorCode.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepository.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryStatRepository.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryStatRepositoryCustom.java
  src/main/java/com/ddobang/backend/domain/diary/repository/DiaryStatRepositoryImpl.java
  src/main/java/com/ddobang/backend/domain/diary/service/DiaryService.java
  src/main/java/com/ddobang/backend/domain/member/controller/MemberController.java
  src/main/java/com/ddobang/backend/domain/member/dto/response/MemberStatResponse.java
  src/main/java/com/ddobang/backend/domain/member/dto/stat/EscapeScheduleStatDto.java
  src/main/java/com/ddobang/backend/domain/member/entity/EscapeScheduleStat.java
  src/main/java/com/ddobang/backend/domain/member/entity/MemberStat.java
  src/main/java/com/ddobang/backend/domain/member/repository/MemberStatRepository.java
  src/main/java/com/ddobang/backend/domain/member/service/MemberService.java
  src/main/java/com/ddobang/backend/domain/member/support/MemberStatCalculator.java
  src/main/java/com/ddobang/backend/domain/member/support/MemberStatScheduler.java
  src/main/java/com/ddobang/backend/domain/stat/dto/ThemeStatResult.java
  src/main/java/com/ddobang/backend/domain/theme/support/ThemeStatCalculator.java
  src/main/java/com/ddobang/backend/global/exception/GlobalExceptionHandler.java
  src/main/java/com/ddobang/backend/global/initdata/BaseInitData.java
  src/main/java/com/ddobang/backend/global/security/CustomUserDetailsService.java
  src/main/java/com/ddobang/backend/global/util/Ut.java
  src/test/java/com/ddobang/backend/domain/diary/controller/DiaryControllerTest.java
  src/test/java/com/ddobang/backend/domain/diary/service/DiaryServiceTest.java
  src/test/java/com/ddobang/backend/domain/member/controller/MemberControllerIntegrationTest.java
  src/test/java/com/ddobang/backend/domain/member/controller/MemberControllerTest.java
  src/test/java/com/ddobang/backend/domain/member/repository/MemberStatRepositoryTest.java
  src/test/java/com/ddobang/backend/domain/member/support/MemberStatCalculatorTest.java
  src/test/java/com/ddobang/backend/domain/theme/support/ThemeStatCalculatorTest.java
  src/test/java/com/ddobang/backend/global/auth/AuthIntegrationTest.java
Labels: refactor, feature, test
